### ISSUE TITLE
Validate the module settings

### ISSUE THREAD

**Issue by jannesblobel** [inlang/monorepo#1451]
https://github.com/inlang/internal/discussions/169

Approach: 
- replace the settings file in plugin JSON with a type-box validation code 
- validate the incoming settings of the plugin settings

**Comment by samuelstroschein** [comment]
## Proposal - add `settingsSchema` property

<img width="466" alt="CleanShot 2023-10-13 at 12 49 18@2x" src="https://github.com/inlang/monorepo/assets/35429197/bd95b4b1-bf6c-4841-a384-cb448ecc90cd">

<img width="323" alt="CleanShot 2023-10-13 at 12 49 57@2x" src="https://github.com/inlang/monorepo/assets/35429197/4de76ae5-baba-4a16-80dc-479067c36fd4">


**Pros**

- always up to date settings schema
- developers don't need to host the schema 
- performance improvements because devs don't need to validate settings on each function call

**Cons**

- ?

**Comment by jannesblobel** [comment]
- move the Pluginsettings validation into the load project file 
- - validate all settings from the project.inlang.json file ( Project settings and module settings ) in loadProject

**Comment by samuelstroschein** [comment]
- move to `resolveModules` for performance reasons
- create a `ModuleHasInvalidSettingsError`
- add `settingsSchema` to `MessageLintRule`

**Comment by samuelstroschein** [comment]
- [ ] use typebox for validation. make comments in message lint rules and plugins that tyepbox must be used. in the future, if demand exists, we can allow manually written JSON schemas with no breaking change (maybe link to a github discussion where people can vote for plain JSON schema support. mention why we decided to use typebox for now)

**Comment by jannesblobel** [comment]
merged with #1507
