### ISSUE TITLE
evaluate search backends

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1469]
## Proposal

Leverage a search backend like Aloglia, Typesense, or something else to fulfill the goal of inlang.com "you will find what you need".

### Selection criterion
```
+ important
o neutral
- not important
```

- [+] ease of usage in JS frontend 
- [+] backend server can be NodeJS/JS
- [o] response time
- [-] pricing 

### Sub-tasks

- [ ] #1470

**Comment by samuelstroschein** [comment]
@floriandwt i recommend using this issue as an update thread on your findings. The main contesters I am aware of are 

- typesense
- algolia
- mellisearch 


Please update the selection criteria if you deem fit

**Comment by floriandwt** [comment]
First insight using Algolia with our registry: every item needs an objectID to get indexed.
<img width="1213" alt="Screenshot 2023-10-16 at 12 36 04 PM" src="https://github.com/inlang/monorepo/assets/92092993/e277fe4f-d98a-452f-9d98-3391d7066597">

**Comment by samuelstroschein** [comment]
@floriandwt i think we generally need unique ids for everything. we can do that manually at first by not storing manifests in an array but an key value object

```
{
  0has8h3: "https://github.com/inlang/inlang/main/marketplace-manifest.json"
  a2i38s: "https://github.com/inlang/inlang/main/marketplace-manifest.json"
}
```

**Comment by floriandwt** [comment]
@samuelstroschein @inlang/website @felixhaeberle here are the results of my research: https://www.loom.com/share/cdef3f90acb0449c8dc003feebaa28f9

In case you won't watch everything, these two have the best experience.
- Algolia
- Orama

<img width="764" alt="Screenshot 2023-10-17 at 4 12 43 PM" src="https://github.com/inlang/monorepo/assets/92092993/134c0dc6-5167-4272-bd45-b818df74c143">

Pricing isn't a criterion so I didn't focus on that. **How important is the response time?** Obviously hard to test because locally it is always faster. In my opinion, that's a "neutral" selection criterion, will edit Samuels comment.

**Comment by samuelstroschein** [comment]
@floriandwt as discussed on a call

- it seems like we should go with algolia 
- hosting via docker containers is too resource intensive 
- aloglia alternatives are really just that. alternatives that are not better when self hosting is not required.

**Comment by floriandwt** [comment]
As I haven't received any strong opinions against it and feel that it is the best solution for us too, I will start implementing Algolia. (syncing with Nils and Niklas first)

**Comment by openscript** [comment]
I've used https://pagefind.app/ in the past and was always happy.

**Comment by openscript** [comment]
@floriandwt You can source dynamic content: https://pagefind.app/docs/node-api/

This would also fit the rather static lix.

**Comment by samuelstroschein** [comment]
We decided on Algolia. 

- it's a business, not an OSS project. meaning, they solve business needs that we have. 
- alogia alternatives are "copycats" with no added value
