### ISSUE TITLE
fix npm workspaces + dependency hell – switch to lerna / rush ?

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/monorepo#1526]
## Problem

In the past, multiple people had problems with our current approach & that dependencies are not correctly updated.

The main problem is with:

```json
"@inlang/json-types": "*",
"@inlang/translatable": "*",
"@inlang/message-lint-rule": "*",
"@inlang/module": "*",
"@inlang/language-tag": "*",
"@inlang/message": "*",
"@inlang/plugin": "*",
```

which doesn't resolve correctly when updated.

## Solution

This issue aims to find a way of tackling this issue and find a new way with another tooling like pnpm + lerna or rush.

> A new approach has to be investigated & tested.

cc @samuelstroschein 

## Related 

- [x] https://github.com/inlang/internal/issues/176

**Comment by samuelstroschein** [comment]
Requirements:

- dependencies need a fixed version when published to npm (pnpm does that)

- changes of dependencies must bump the consumers version too for re-deployment (changeset seems buggy here)

pnpm, lerna, rush should be evaluated for 

- maintenance (lerna and rush have company backing, pmpm is a one man show)

- easy of use (we don't want everyone to learn a complicated stack)

**Comment by samuelstroschein** [comment]
@olivermrbl are you running into those kinds of issues at medusa too? 

i saw that you are using npm workspaces. wondering how you deal with this versioning problem.

**Comment by olivermrbl** [comment]
@samuelstroschein, yes, we and our users are experiencing similar issues. Funny enough, I am investigating a better approach these weeks.

The immediate solution I had in mind was to bump all packages to a fixed version when we cut a new release so that we at least know that installing the `@latest` versions will work correctly. This, in combination with a new CLI command that will update users' packages, could be a way to go.

However, I realise this is not a very elegant solution, so I am curious to hear what you guys have in mind.

**Comment by felixhaeberle** [comment]
Actually, there is a new kid on the block I've not considered before because they are mainly in the component space, but it seems that they also have figured out a lot of problems we are dealing with: https://bit.dev/blog/painless-monorepo-dependency-management-with-bit-l4f9fzyw/

**Comment by samuelstroschein** [comment]
@felixhaeberle bit seems opinionated; requiring lots of education. the package.json workflow is unbeatably simple and known. 

@olivermrbl if versioning of dependencies is the only problem, pnpm offers a solution. i am hesitant about pnpm though because it is maintained by only one person. 

[rush](https://rushjs.io/) from Microsoft seems "most production ready" but breaks the known npm/pnpm install workflow

**Comment by olivermrbl** [comment]
FWIW, I fleshed out our issue in [this PR](https://github.com/medusajs/medusa/pull/5383), which introduces a way to reduce the amount of problems our users will have with dependencies in their projects.

However, this is far from perfect. It does not solve the root cause, which is mismanagement of dependencies and peer dependencies. Something we've neglected since forever.

Workspaces can be a pain to work with...

**Comment by samuelstroschein** [comment]
@olivermrbl Thanks for sharing. Seems like we need to switch to pnpm (or yarn) in any case as NPM does not support "workspace: *" dependency declarations.

**Comment by samuelstroschein** [comment]
@felixhaeberle any progress?

**Comment by felixhaeberle** [comment]
not yet, had a few other things to do in preparation to the summit e.g. fixing ide extension & updating m function matcher to latest import syntax + implementing paraglide vite plugin.

buut: this will be tackled this week!
