### ISSUE TITLE
license is gone from product pages

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1627]
## Problem 

People specifcally asked us what license paraglide js is under. The information is not displayed anymore. 

## Proposal

Display the license again

**Comment by flornkm** [comment]
@samuelstroschein can't reproduce what the issue is – the license is still displayed, below the more necessary information as discussed. Have tested it in all major browsers, gets displayed.

Do you have further information? Or do you mean the "cards"? I don't know if we should display the license there too.

**Comment by samuelstroschein** [comment]
Completely hidden, not discoverable. The license is crucial for dev tool adoption. I would put it to the top as we had it before. You can leave out the keywords to save space

<img width="1379" alt="CleanShot 2023-11-13 at 08 54 19@2x" src="https://github.com/inlang/monorepo/assets/35429197/df76fce0-39c1-4f85-acba-6f2df5ef664c">

**Comment by flornkm** [comment]
@samuelstroschein aaah okay, got it. Will put it back to the top.

**Comment by flornkm** [comment]
Implemented with https://github.com/inlang/monorepo/commit/bc5310560ad2f89fb8c76f20caf91ad2e7325493
