### ISSUE TITLE
[Fink] Fink editor contributers ask for guide

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/monorepo#1750]
## Problem 
People asking for a contribution guide 

"If aggregating all inputs on documentation in here I have my point:
- how to use guide for Inlang editor for people who use it to contribute to OSS projects via Inlang
- basic simple usage - how to make references, what statuses mean, etc. ('Missing translation' pop-up textation was confusing to me as a newcomer)" from @stmr, https://github.com/inlang/monorepo/issues/1667

@inlang/editor @NiklasBuchfink do you think that makes sense?

**Comment by NiklasBuchfink** [comment]
I guess there are more discussion points:
1. **Guide**:
It makes sense to have a guide in a form like [this](https://help.remnote.com/en/articles/8300602-contributing-translations-for-remnote). Projects can refer to it and it is a good starting point for anyone who only uses the editor to contribute to a project. 
2. **How to make references**:
Could you clarify? We got the reference language or source language, which is usually the English translation and is provided by the maintainers. If the reference language contains variables or variable references, these are highlighted and can be selected via a floating menu when clicking into a text field of another language. 
Currently there is no way to create a new variableReference within the editor. Do you think this is needed for the reference language? Or is it just the selection of a variableReference and we have a bug that this floating menu is empty or absent?
3. **What statuses mean**:
Please correct me, if I'm wrong. It's not that the wording of  "missing translation", which is quite descriptive with an empty text box next to it. It's about better status descriptions within the pop-up text, right? We need to update the description so that it is easy to understand. This could also affect other apps that display the description.

**Comment by NiklasBuchfink** [comment]
Update on 2. :
We have a bug that the floating menu doesn't show up occasionally. This makes it confusing for the user. I got it on the list for this week.

**Comment by stmr** [comment]
1. That link is exactly what I was looking for when first trying to kickstart with Inlang!
2. By references I meant 
![Screenshot 2023-11-27 at 12-22-38 stmr_AppFlowy](https://github.com/inlang/monorepo/assets/1045974/cc8e6ed1-f6f8-4b3a-a4cf-3884ddc64edb) and there is bug for them not showing occasionally that's why the confusion but the linked guide from 1. would be informative enough to deduct it is broken and I am not doing anything wrong or missing something
3. It is explanatory when working properly but I am getting both green tick and "missing translation" which confused me. I was trying to find other occurrences of the phrase to see if there are more missing translations (also another bug I've created)

**Comment by NiklasBuchfink** [comment]
We have a guide now: https://inlang.com/g/6ddyhpoi/guide-nilsjacobsen-contributeTranslationsWithFink
Thank you @NilsJacobsen for writing this 👏 

@stmr Let us know if this would have helped you in your first steps with the Fink editor :)

I'll wait until #1762 is merged and will add a link to the Fink product page.

**Comment by stmr** [comment]
What a blissful guide! Thanks! @NiklasBuchfink @NilsJacobsen
