### ISSUE TITLE
Move inlang apps to their brandable subdomains

### ISSUE THREAD

**Issue by flornkm** [inlang/monorepo#1848]
## Problem 
We haven't moved the apps to the subdomains yet. But we want to accurately link these pages which now have their own branding.
Optimizing these pages for SEO requires them to be hosted on their subdomain, otherwise, we fail in terms of a good ranking and links may be broken in the future (obviously redirects have to be there).

## Proposal
Move the following apps to their subdomains:
- 🛑 `inlang SDK` -> `sdk.inlang.com` @NilsJacobsen [WAIT UNTIL REQUIREMENTS COME UP]
- [x] #1873
- [x] `inlang Manage` -> `manage.inlang.com` @flornkm 

## Additional information

**Planning to finish this by the second half of calendar week 50 when Niklas is back**

**Comment by flornkm** [comment]
@NilsJacobsen wasn't the strategy you've discussed with @samuelstroschein that the SDK gets more and more like `sell.amazon.com` or did I understand anything wrong? I wasn't attending the initial discussion, I think I've just quickly spoke with someone about it.

**Comment by samuelstroschein** [comment]
@flornkm yes. but the requirement to split inlang.com from a "seller page" because the tech requirements are so different doesn't exist yet. for fink and manage they do (CSR vs SSR, no SEO vs SEO, etc). 

Btw, here is a list of subdomains from other marketplaces:

```
partnerportal.zalando.com
sell.amazon.com
play.google.com/console
etsy.com/sell
```

Unclear what we should choose. I propose to hold off the unbundling until (tech) requirements come up

**Comment by flornkm** [comment]
Agree on that. Let's wait with the partner page.

**Comment by flornkm** [comment]
Everything done for now.
fink.inlang.com and manage.inlang.com
