### ISSUE TITLE
paraglide recompile gets triggered too often

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/monorepo#1872]
## Problem 

Sometimes, when working with paraglide in dev mode, it recompiles up to 1500 times, causing slow-downs in memory even on my 64GB M1 Max haha which handles even the most absurd loads. 

<img width="746" alt="Bildschirmfoto 2023-12-12 um 10 52 20" src="https://github.com/inlang/monorepo/assets/34959078/936b350c-0744-4676-bbbe-677cbeb6624a">

## Proposal

I don't know why this is happening, but we probably need a debouncer for certain file watches or something. Leave it open to @LorisSigrist to decide and investigate.

**Comment by LorisSigrist** [comment]
The root cause here is that we're using `fs.watch` as a watcher in the SDK. If that were to be replaced with something less terrible this wouldn't happen.
In the meantime what I could do is to check if the messages actually changed before recompiling. That would at least help a bit. (although the check would still get run all the time)

**Comment by felixhaeberle** [comment]
Thanks!:)
