### ISSUE TITLE
[bug] cli validate is not doing anything

### ISSUE THREAD

**Issue by NilsJacobsen** [inlang/monorepo#1884]
## Problem: no error or success when validating
![image](https://github.com/inlang/monorepo/assets/58360188/a4b8ba61-be59-462a-882d-5793e577151e)

- No error
- no success
- just exits

## Repoduction

- Open monorepo
- type `npx @inlang/cli validate --project ../project.inlang`

@inlang/cli

**Comment by felixhaeberle** [comment]
I'm looking into this.

**Comment by felixhaeberle** [comment]
It seems that this is either a @inlang/lix or @inlang/sdk bug. I could track it down to 

https://github.com/inlang/monorepo/blob/2c314af80887f299cb614549e1e542c15e8a3b7e/inlang/source-code/sdk/src/migrations/migrateToDirectory.ts#L18

-> where the code terminates without any error causing this strange behavior. Reassigning this issue to @samuelstroschein who wrote the code initially. 

Again, this took me 30min+ which makes very clear that some person for the SDK is needed.

**Comment by samuelstroschein** [comment]
I will remove the migration code.

**Comment by samuelstroschein** [comment]
@felixhaeberle the bug was in the CLI. 

The action was not awaited. The CLI exited the process before loading a project. 

<img width="693" alt="CleanShot 2023-12-15 at 11 52 50@2x" src="https://github.com/inlang/monorepo/assets/35429197/873f8ebb-540a-4a34-b322-a41b09f4828d">

---

I did not remove the migration code because cal.com is not migrated yet (urgh?). I will add telemetry that captures if a migration is still executing. Super important to have #1891 for that.
