### ISSUE TITLE
Reactive filesystem for the editor to avoid bugs and performance issues

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#839]
## Problem

The inlang editor naively re-renders and re-initializes state on any changed file in the filesystem, see issues like https://github.com/inlang/inlang/issues/838#issuecomment-1560745678. 

**Example**

1. After every `writeFile` call the editor naively calls a `setFsChange` signal. 

https://github.com/inlang/inlang/blob/a47ac5d942388f0718e48f36cd22ced3b01f73cd/source-code/website/src/pages/editor/%40host/%40owner/%40repository/index.page.tsx#L198-L199

2. All filesystem-dependent code listens to `fsChange` to re-run reactive code. 

https://github.com/inlang/inlang/blob/a47ac5d942388f0718e48f36cd22ced3b01f73cd/source-code/website/src/pages/editor/%40host/%40owner/%40repository/State.tsx#L242-L244

`fsChange` triggers if _any_ change occurs. Thus, the editor constantly re-renders and re-builds state leaded to performance issues and bugs. 

## Proposal

Create a new filesystem implementation for SolidJS that is reactive.

```ts
// the readFile call should be reactive, triggering the following code to re-run 
// when the "/inlang.config.js" file changes
const config = await fs.readFile("/inlang.config.js", { encoding: "utf-8" })
``` 

The implementation could wrap `memoryFs` under the hood.

**Comment by araknast** [comment]
I think there is a hidden difficulty here in that we will need they filesystem to be reactive, while also maintaining full node compatibility, since we also need to pass it to isomorphic-git. Currently I see 3 ways of going about this:
1. Create a reactive filesystem that adheres to the node api, but returns signals instead of promises. We would then need to create a shallow wrapper that converts these signals to the expected node types.
3. Create a reactive filesystem that _does not_ adhere to the node api, something like https://github.com/Akryum/reactive-fs. This would then need to be wrapped with a full `NodeishFilesystem` wrapper.
4. Create a reactive filesystem which implements a superset of the `NodeishFilesystem` api. In this case, users will be able to create a signal which 'subscribes' to updates on a particular file or directory. Then a resource can be created which updates the file data when the signal is triggered.

(3) Would entail the least amount of development work, and would not require us to define a new filesystem api. (1) and (2) entail potentially better dx, but would require us to define a new api that is then wrapped. 

This is all based on my own understanding of the SolidJS reactive system. Since you are probably more familiar with it than I am, I'm curious to hear your thoughts and how you might go about this.

**Comment by samuelstroschein** [comment]
> I think there is a hidden difficulty here in that we will need the filesystem to be reactive, while also maintaining full node compatibility since we also need to pass it to isomorphic-git.

I assume that you refer to `NodeishFilesystem` with "full node compatibility" (which would mean subset compatibility). 

> This is all based on my own understanding of the SolidJS reactive system. Since you are probably more familiar with it than I am, I'm curious to hear your thoughts and how you might go about this.

Making `NodeishFilesystem` reactive should be easy peasy. 

Think of signals as a) an accessor which is a function and b) the accessor listens to a setter. A quick comparison to React:

```ts
// in react
const [x, setX] = useState(0)

console.log(x)
>> 0

// in solid/signals
const [x, setX] = createSignal(0)

console.log(x)
>> Function 

console.log(x())
>> 0 
```

An example with `NodeishFilesystem`: `readFile` is an accessor, and `writeFile` is a setter.  Since `NodeishFilesystem` only consists of function calls, aka "accessors and setters", making `NodeishFilesystem` reactive should be easy peasy. There is no need to change any APIs/introduce supersets/etc. 

The only change seems to be replacing `fsMap` and `fsStats` with a reactive implementation, see https://github.com/solidjs-community/solid-primitives/tree/main/packages/map#solid-primitivesmap. 

If we are lucky, implementing the reactive filesystem is ≈3 lines of code by passing the reactive maps to `createMemoryFs`. Here is pseudocode: 

```ts
import { ReactiveMap } from "@solid-primitives/map";

function createSolidMemoryFs(){ 
  const memfs = createMemoryFs({ fsMap: new ReactiveMap(), fsStats: new ReactiveMap() })
  return memfs
}
```

**Comment by araknast** [comment]
Ok good, was not aware of `@solid-primitives/map`. I agree this should hopefully be fairly trivial then.

**Comment by felixhaeberle** [comment]
@samuelstroschein We now have reactivity within inlang/app – do we also need to "close" reactivity ring with a reactive filesystem in @inlang/lix ? Who should be assigned?

**Comment by samuelstroschein** [comment]
@felixhaeberle This issue can be closed in favor of https://github.com/orgs/inlang/discussions/1295
